#!/bin/bash

# Program to output a system information page

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date)
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

# d=$(ls -l ~/Desktop) <-- assigns d to the ls of desktop
# cp $TITLE ${TITLE}.txt <-- to tell bash that it is just the TITLE variable and not the TITLE.txt variable
# <PRE> preseves the output of the command
report_uptime() {
	cat <<- _EOF_
		<H2>System Uptime</H2>
		<PRE>$(uptime)</PRE> 
		_EOF_
	return
}

report_disk_space() {
	cat <<- _EOF_
		<H2>Disk Space Utilization</H2>
		<PRE>$(df -h)</PRE>
		_EOF_
	return 
}

report_home_space() {
	cat <<- _EOF_
		<H2>Home Space Utilization</H2>
		<PRE>$(du -sh /Users/*)</PRE>
		_EOF_
	return
}

cat << _EOF_
<HTML>
 <HEAD>
	<TITLE>$TITLE</TITLE>
  <HEAD>
  <BODY>
	<H1>$TITLE</H1>
	<P>$TIME_STAMP</P>
	$(report_uptime)
	$(report_disk_space)
	$(report_home_space)
  <BODY>
</HTML>
_EOF_
