#!/bin/bash

# how to access command line parameters
# for more than 9, use ${number} like ${10}
# $# shows how many 

echo "there were $# arguents"

echo "\$0 = $0 \$1 = $1 \$2 = $2 \$3 = $3 \$4 = $4  \$5 = $5 \$6 = $6 \$7 = $7 \$8 = $8 \$9 = $9"
