#!/bin/bash

# while loop

count=1

while [ $count -le 5 ]; do
	echo "$count"
	count=$((count + 1))
done

echo "Finished"

# until loop (continues until it recieves a 0 exit status

count=1

until [ $count -gt 5 ]; do
	echo $count
	count=$((count + 1))
done

echo "Finished until loop"
